kells_back_homepage:
    path:     /admin/
    defaults: { _controller: KellsBackBundle:Default:index }
    
usuarios:
    path:     /admin/usuarios
    defaults: { _controller: KellsBackBundle:Default:usuarios }


addUser:
    path:     /admin/user/add
    defaults: { _controller: KellsBackBundle:Default:addUser }
    
saveUser:
    path:     /admin/user/save
    defaults: { _controller: KellsBackBundle:Default:saveUser }

modifyUser:
    path:     /admin/user/edit/{id}
    defaults: { _controller: KellsBackBundle:Default:modifyUser }
        
deleteUser:
    path:     /admin/user/delete/{id}
    defaults: { _controller: KellsBackBundle:Default:deleteUser }

concesionarias:
    path:     /admin/concesionarias
    defaults: { _controller: KellsBackBundle:Default:concesionarias }


addLicensee:
    path:     /admin/licensee/add
    defaults: { _controller: KellsBackBundle:Default:addLicensee }    

saveLicensee:
    path:     /admin/licensee/save
    defaults: { _controller: KellsBackBundle:Default:saveLicensee }

modifyLicensee:
    path:     /admin/licensee/edit/{id}
    defaults: { _controller: KellsBackBundle:Default:modifyLicensee }

deleteLicensee:
    path:     /admin/licensee/delete/{id}
    defaults: { _controller: KellsBackBundle:Default:deleteLicensee }
    
alarfin_login_view:
    path:     /admin/login/
    defaults: { _controller: KellsBackBundle:Default:adminLogin }
    
admin_check:
    pattern: /admin/login_check
    
logout:
    pattern: /admin/logout
    
publicaciones_usuario:
    path:     /admin/usuarios/publicaciones/{userId}
    defaults: { _controller: KellsBackBundle:Default:publicacionesUsuario }

    
configuracion:
    path:     /admin/configuracion
    defaults: { _controller: KellsBackBundle:Default:configuration }
    
saveChanges:
    path:     /admin/saveconfiguracion
    defaults: { _controller: KellsBackBundle:Default:saveChanges }
    
creditos:
    path:     /admin/creditos
    defaults: { _controller: KellsBackBundle:Default:creditos }
 
verCredito:
    path:     /admin/creditos/{id}
    defaults: { _controller: KellsBackBundle:Default:showCredito }
    
alarfin:
    path:     /admin/alarfin
    defaults: { _controller: KellsBackBundle:Default:alarfin }
    
agregar_alarfin:
    path:     /admin/alarfin/agregar
    defaults: { _controller: KellsBackBundle:Default:agregarAlarfin }
    
save-alarfin:
    path:     /admin/alarfin/save
    defaults: { _controller: KellsBackBundle:Default:saveAlarfin }
    
deleteAlarfin:
    path:     /admin/alarfin/delete/{id}
    defaults: { _controller: KellsBackBundle:Default:deleteAlarfin }
    
editar-alarfin:
    path:     /admin/alarfin/editar/{id}
    defaults: { _controller: KellsBackBundle:Default:editarAlarfin }
    
publicaciones:
    path:     /admin/publicaciones
    defaults: { _controller: KellsBackBundle:Default:publicaciones }
    
agregarPublicacion:
    path:     /admin/publicaciones/agregar
    defaults: { _controller: KellsBackBundle:Default:agregarPublicacion }
    
route_to_retrieve_model:
    pattern: /getModels/
    defaults: {_controller: KellsFrontBundle:Default:getModels}
    options:
        expose: true
        
route_to_retrieve_city:
    pattern: /getCities/
    defaults: {_controller: KellsFrontBundle:Default:getCities}
    options:
        expose: true

admin_publish:
    path:     /admin/publicaciones/publish/
    defaults: { _controller: KellsBackBundle:Default:publish  }
    
editar-publicacion:
    path:     /admin/publicaciones/editar/{carId}
    defaults: { _controller: KellsBackBundle:Default:editCar }