kells_back_homepage:
    path:     /admin/
    defaults: { _controller: KellsBackBundle:Default:index }
    
usuarios:
    path:     /admin/usuarios
    defaults: { _controller: KellsBackBundle:Default:usuarios }

    
deleteUser:
    path:     /admin/user/delete/{id}
    defaults: { _controller: KellsBackBundle:Default:deleteUser }
    
alarfin_login_view:
    path:     /admin/login/
    defaults: { _controller: KellsBackBundle:Default:adminLogin }
    
admin_check:
    pattern: /admin/login_check
    
logout:
    pattern: /admin/logout
    
publicaciones_usuario:
    path:     /admin/usuarios/publicaciones/{userId}
    defaults: { _controller: KellsBackBundle:Default:publicacionesUsuario }

    
configuracion:
    path:     /admin/configuracion
    defaults: { _controller: KellsBackBundle:Default:configuration }
    
saveChanges:
    path:     /admin/saveconfiguracion
    defaults: { _controller: KellsBackBundle:Default:saveChanges }
    
creditos:
    path:     /admin/creditos
    defaults: { _controller: KellsBackBundle:Default:creditos }
 
verCredito:
    path:     /admin/creditos/{id}
    defaults: { _controller: KellsBackBundle:Default:showCredito }
    
alarfin:
    path:     /admin/alarfin
    defaults: { _controller: KellsBackBundle:Default:alarfin }
    
agregar_alarfin:
    path:     /admin/alarfin/agregar
    defaults: { _controller: KellsBackBundle:Default:agregarAlarfin }
    
save-alarfin:
    path:     /admin/alarfin/save
    defaults: { _controller: KellsBackBundle:Default:saveAlarfin }
    
deleteAlarfin:
    path:     /admin/alarfin/delete/{id}
    defaults: { _controller: KellsBackBundle:Default:deleteAlarfin }
    
editar-alarfin:
    path:     /admin/alarfin/editar/{id}
    defaults: { _controller: KellsBackBundle:Default:editarAlarfin }