kells_front_homepage:
    path:     /
    defaults: { _controller: KellsFrontBundle:Default:index }
    
publicaciones:
    path:     /publicaciones
    defaults: { _controller: KellsFrontBundle:Default:publicaciones }
    
concesionarias:
    path:     /concesionarias
    defaults: { _controller: KellsFrontBundle:Default:concesionarias }

details:
    path:     /details/{carId}
    defaults: { _controller: KellsFrontBundle:Default:details }
    
searchCar:
    path:     /searchCar
    defaults: { _controller: KellsFrontBundle:Default:searchCar }
    
userRegistration:
    path:     /userRegistration
    defaults: { _controller: KellsFrontBundle:Default:userRegistration }
    
licenseeRegistration:
    path:     /licenseeRegistration
    defaults: { _controller: KellsFrontBundle:Default:licenseeRegistration }
    
licensee_create:
    path:     /licenseeRegistration/confirm
    defaults: { _controller: KellsFrontBundle:Default:licenseeConfirm }
    
licensee_confirm:
    path:     /licensee/register/confirm/{token}
    defaults: { _controller: KellsFrontBundle:Default:licenseeRegisterConfirm }

licensee_message_confirm:
    path:     /licensee/register/message/
    defaults: { _controller: KellsFrontBundle:Default:registerMessageConfirm }
    
user_create:
    path:     /userRegistration/confirm
    defaults: { _controller: KellsFrontBundle:Default:userConfirm }
    
user_confirm:
    path:     /user/register/confirm/{token}
    defaults: { _controller: KellsFrontBundle:Default:userRegisterConfirm }

user_message_confirm:
    path:     /user/register/message/
    defaults: { _controller: KellsFrontBundle:Default:registerMessageConfirm }
    
user_login_view:
    path:     /user/login/
    defaults: { _controller: KellsFrontBundle:Default:userLogin }
    
login_check:
    pattern: /user/login_check
logout:
    pattern: /user/logout
    
user_myPublications:
    path:     /user/myPublications/
    defaults: { _controller: KellsFrontBundle:Default:userMyPublications }
    
user_toPublish:
    path:     /user/toPublish/
    defaults: { _controller: KellsFrontBundle:Default:toPublish }

user_toPublish_error:
    path:     /user/toPublish/{message}
    defaults: { _controller: KellsFrontBundle:Default:toPublish }
    
    
route_to_retrieve_model:
    pattern: /getModels/
    defaults: {_controller: KellsFrontBundle:Default:getModels}
    options:
        expose: true
        
route_to_retrieve_city:
    pattern: /getCities/
    defaults: {_controller: KellsFrontBundle:Default:getCities}
    options:
        expose: true
        
publish:
    path:     /publish/
    defaults: { _controller: KellsFrontBundle:Default:publish  }
    
to_finalize:
    path:     /finalize/
    defaults: { _controller: KellsFrontBundle:Default:toFinalize  }
    
to_edit:
    path:     /edit/
    defaults: { _controller: KellsFrontBundle:Default:toEdit  }
    
republish:
    path:     /republish/
    defaults: { _controller: KellsFrontBundle:Default:republish  }
    
creditRequest:
    path:     /creditRequest/
    defaults: { _controller: KellsFrontBundle:Default:showCreditRequest }
    
creditRequestSuccess:
    path:     /creditRequest/Success
    defaults: { _controller: KellsFrontBundle:Default:showCreditRequestSuccess }
    
credit:
    path:     /credit/
    defaults: { _controller: KellsFrontBundle:Default:credit }
    
simulador:
    path:     /simulador/
    defaults: { _controller: KellsFrontBundle:Default:showSimulador }
    
simularCuotas:
    pattern: /simularCuotas/
    defaults: {_controller: KellsFrontBundle:Default:simularCuotas }
    options:
        expose: true

getValorCuotas:
    pattern: /valorCuotas/
    defaults: {_controller: KellsFrontBundle:Default:getValorCuotas }
    options:
        expose: true
        
olvideContrasena:
    path:     /recuperar-contrasena
    defaults: { _controller: KellsFrontBundle:Default:recuperarUser }
    
recuperarUser:
    path:     /recuperar-contrasena/message
    defaults: { _controller: KellsFrontBundle:Default:recuperarUserContrasena }
    
consultar:
    path:     /consultar
    defaults: { _controller: KellsFrontBundle:Default:enviarConsulta }
   
filterResults:
    path:     /filterResults/
    defaults: { _controller: KellsFrontBundle:Default:filterResults }
    
removeFilter:
    path:     /removeFilter/
    defaults: { _controller: KellsFrontBundle:Default:removeFilter }
    
registerNow:
    path:     /registerMe/
    defaults: { _controller: KellsFrontBundle:Default:registerNow }

contacto:
    path:     /contact/
    defaults:
        _controller: FrameworkBundle:Template:template
        template:     'KellsFrontBundle:Default:contacto.php.twig'
        maxAge: 86400
        sharedMaxAge: 86400
        private: false

empresa:
    path:     /empresa/
    defaults:
        _controller: FrameworkBundle:Template:template
        template:     'KellsFrontBundle:Default:la-empresa.php.twig'
        maxAge: 86400
        sharedMaxAge: 86400
        private: false

productos-y-servicios:
    path:     /productos-y-servicios/
    defaults:
        _controller: FrameworkBundle:Template:template
        template:     'KellsFrontBundle:Default:productos-y-servicios.php.twig'
        maxAge: 86400
        sharedMaxAge: 86400
        private: false
      
preguntas-frecuentes:
    path:     /preguntas-frecuentes/
    defaults:
        _controller: FrameworkBundle:Template:template
        template:     'KellsFrontBundle:Default:preguntas-frecuentes.php.twig'
        maxAge: 86400
        sharedMaxAge: 86400
        private: false
        
links-de-interes:
    path:     /links-de-interes/
    defaults:
        _controller: FrameworkBundle:Template:template
        template:     'KellsFrontBundle:Default:links-de-interes.php.twig'
        maxAge: 86400
        sharedMaxAge: 86400
        private: false
        
prendarios-individuos:
    path:     /productos-y-servicios-creditos-prendarios-individuos/
    defaults:
        _controller: FrameworkBundle:Template:template
        template:     'KellsFrontBundle:Default:prendarios-individuos.php.twig'
        maxAge: 86400
        sharedMaxAge: 86400
        private: false

prendarios-corporativos:
    path:     /productos-y-servicios-creditos-prendarios-corporativos/
    defaults:
        _controller: FrameworkBundle:Template:template
        template:     'KellsFrontBundle:Default:prendarios-corporativos.php.twig'
        maxAge: 86400
        sharedMaxAge: 86400
        private: false
             
compra-cheques:
    path:     /productos-y-servicios-creditos-compra-de-cheques/
    defaults:
        _controller: FrameworkBundle:Template:template
        template:     'KellsFrontBundle:Default:compra-de-cheques.php.twig'
        maxAge: 86400
        sharedMaxAge: 86400
        private: false
compra-facturas:
    path:     /productos-y-servicios-creditos-compra-de-facturas/
    defaults:
        _controller: FrameworkBundle:Template:template
        template:     'KellsFrontBundle:Default:compra-de-facturas.php.twig'
        maxAge: 86400
        sharedMaxAge: 86400
        private: false
        
contacto-enviar:
    path:     /contacto-gracias/
    defaults: { _controller: KellsFrontBundle:Default:contactoEnviar }
    
allCars:
    path:     /allcars
    defaults: { _controller: KellsFrontBundle:Default:allCars }
    
    
overcomePublications:
    path:     /overcomePublications
    defaults: { _controller: KellsFrontBundle:Default:overcomePublications }