parameters:
#    kells_front.example.class: Kells\Bundle\FrontBundle\Example

services:
#    kells_front.example:
#        class: %kells_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
