security:
    encoders:
        Kells\Bundle\FrontBundle\Entity\User: plaintext
        Kells\Bundle\FrontBundle\Entity\Licensee: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        chain_provider:
            chain:
                providers: [user_db, licensee_db]
        user_db:
            entity: { class: Kells\Bundle\FrontBundle\Entity\User, property: mail }
        licensee_db:
            entity: { class: Kells\Bundle\FrontBundle\Entity\Licensee, property: mail }

    firewalls:
        user_secured_area:
            pattern: /.*
            provider: user_db
            form_login:
                login_path: /user/login
                check_path: /user/login_check
                remember_me: true
                username_parameter: _mail
                password_parameter: _password
                default_target_path:            /user/myPublications
                target_path_parameter:          _target_path
            logout:
                path: /user/logout
                target: /
            remember_me:
                key: MiClaveSegura
                lifetime: 1800
                path: /.*
                domain: ~
            security: true
            anonymous: true

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/user/myPublications, roles: ROLE_USER}