parameters:
#    kells_licensee.example.class: Kells\LicenseeBundle\Example

services:
#    kells_licensee.example:
#        class: %kells_licensee.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
